[project]
name = "ansible-role-git"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "molecule>=25.9.0",
    "molecule-plugins[podman]>=25.8.12",
]
